### ISSUE TITLE
demo.tar文件好像损坏了，解压不了

### ISSUE THREAD

**Issue by shellycsy** [LowinLi/Text-Summarizer-Pytorch-Chinese#18]
如题，能麻烦您重新上传一下吗？谢谢！

**Comment by LowinLi** [comment]
直接把demo.tar文件放在根目录下就可以，不必解压，代码会自动读取这个模型。

https://github.com/LowinLi/Text-Summarizer-Pytorch-Chinese/blob/master/web.py#L18

确切的说，它应该不是一个压缩文件。只是[英文原版](https://github.com/rohithreddy024/Text-Summarizer-Pytorch)的代码如此，我没有改动。

**Comment by shellycsy** [comment]
好的 谢谢！



------------------ 原始邮件 ------------------
发件人: Lowin ***@***.***&gt;
发送时间: 2021年4月19日 10:01
收件人: LowinLi/Text-Summarizer-Pytorch-Chinese ***@***.***&gt;
抄送: shellycsy ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[LowinLi/Text-Summarizer-Pytorch-Chinese] demo.tar文件好像损坏了，解压不了 (#18)





 
直接把demo.tar文件放在根目录下就可以，不必解压，代码会自动读取这个模型。
 
https://github.com/LowinLi/Text-Summarizer-Pytorch-Chinese/blob/master/web.py#L18
 
确切的说，它应该不是一个压缩文件。只是英文原版的代码如此，我没有改动。
