### ISSUE TITLE
有详细的项目工作流程吗？

### ISSUE THREAD

**Issue by HelloWorldlry** [LowinLi/Text-Summarizer-Pytorch-Chinese#2]
我自己照着基于RNN的英文摘要改了一下生成中文的
数据的预处理已经完成，参考的是川大的nlp文本预处理
但是可能因为刚接触nlp，模型构建Attention Layer一直在出错
不知道dalao有没有详细的项目工作流程或者一些思路参考什么的
详细注释也行啊
或者我的邮箱1250336060@qq，加个微信QQ请教一下

**Comment by LowinLi** [comment]
可以share下报错吗

**Comment by HelloWorldlry** [comment]
我用的是windows，不是linux，所以想参考一下你的思路或者流程

**Comment by HelloWorldlry** [comment]
因为我用的是windows，不是linux，所以想参考一下你的思路或者流程




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LowinLi/Text-Summarizer-Pytorch-Chinese"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月18日(星期六) 下午5:28
收件人:&nbsp;"LowinLi/Text-Summarizer-Pytorch-Chinese"<Text-Summarizer-Pytorch-Chinese@noreply.github.com&gt;;
抄送:&nbsp;"哈哈哈"<1250336060@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [LowinLi/Text-Summarizer-Pytorch-Chinese] 有详细的项目工作流程吗？ (#2)





 
可以share下报错吗

**Comment by LowinLi** [comment]
其实我仅仅是重复了一遍Text-Summarizer-Pytorch项目在汉语上的实现，填了写坑。

**Comment by HelloWorldlry** [comment]
我用虚拟机搭了一个ubuntu环境跑了一下，东西都下好放根目录了，执行
sudo docker-compose up


出现下面的问题



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LowinLi/Text-Summarizer-Pytorch-Chinese"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月20日(星期一) 下午5:14
收件人:&nbsp;"LowinLi/Text-Summarizer-Pytorch-Chinese"<Text-Summarizer-Pytorch-Chinese@noreply.github.com&gt;;
抄送:&nbsp;"哈哈哈"<1250336060@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [LowinLi/Text-Summarizer-Pytorch-Chinese] 有详细的项目工作流程吗？ (#2)





 
其实我仅仅是重复了一遍Text-Summarizer-Pytorch项目在汉语上的实现，填了写坑。

**Comment by LowinLi** [comment]
看不到您贴的问题呢？

**Comment by HelloWorldlry** [comment]
![image](https://user-images.githubusercontent.com/40568499/88016865-f833ed00-cb56-11ea-9168-666d2a111fcf.png)

**Comment by LowinLi** [comment]
图片失效了？

**Comment by HelloWorldlry** [comment]
啊，我这边都能看到啊

**Comment by HelloWorldlry** [comment]
heUowor1d(ryuburttu: —/PycharmProjects/Text-Summarlzer.Pytorch-Chlnese 0 File Edit View Search Terminal Help -
Step 6/6 : CMD [“python”, “web.py”)
- - -> Running in adobScceSdf6
Removing tnterriediate container ad6bSccesdfe
- - -> fda3ed7ffi5d
Successfully built fda3ed7ffl5d
Successfully tagged abstract:latest
WARNING: Image for service web-i was built because it did not already exist. To rebuild this triage you must use ‘docker-compose build’ or ‘docker-compose up - -b ufld’.
Creating abstract_el ... done Attaching to abstract_el
abstract_01 eze-e-i l:48:3O,766 - data_uttl.tog - INFO - logiJ
abstract_01 I Serving Flask app “web’ (lazy loading)
abstract_01 I * Environment: production
abstract_01 I WARNING: Do not use the develop.’ent server in a production envi
ronrient.
abstract_01 I Use a production WSGI server instead.
abstract_01 I * Debug mode: off
abstract_01 I * Running on http://0.0.0.0:5060/ (Press CTRLeC to quit)
abstract_01 I 172.18.0.1 - - [21/Jul/2020 10:55:37] “CFT / HTTPI1 1” 44-
abstract_01 I 172.18.0.1 - - [2lflut/2020 10:55:37] CET /favtcon.tco HTTP/l.1

**Comment by HelloWorldlry** [comment]
heUowor1d(ryuburttu: —/PycharmProjects/Text-Summarlzer.Pytorch-Chlnese 0 File Edit View Search Terminal Help -
Step 6/6 : CMD [“python”, “web.py”)

-> Running in adobScceSdf6
Removing tnterriediate container ad6bSccesdfe
-> fda3ed7ffi5d
Successfully built fda3ed7ffl5d
Successfully tagged abstract:latest
WARNING: Image for service web-i was built because it did not already exist. To rebuild this triage you must use ‘docker-compose build’ or ‘docker-compose up - -b ufld’.
Creating abstract_el ... done Attaching to abstract_el
abstract_01 eze-e-i l:48:3O,766 - data_uttl.tog - INFO - logiJ
abstract_01 I Serving Flask app “web’ (lazy loading)
abstract_01 I * Environment: production
abstract_01 I WARNING: Do not use the develop.’ent server in a production envi
ronrient.
abstract_01 I Use a production WSGI server instead.
abstract_01 I * Debug mode: off
abstract_01 I * Running on http://0.0.0.0:5060/ (Press CTRLeC to quit)
abstract_01 I 172.18.0.1 - - [21/Jul/2020 10:55:37] “GET / HTTP/1.1” 404-
abstract_01 I 172.18.0.1 - - [2lflut/2020 10:55:37] "GET /favicon.ico HTTP/1.1"404-

**Comment by LowinLi** [comment]
restful请求发错了，应该是post请求，不是get请求

**Comment by LowinLi** [comment]
readme中：

curl -H "Accept: application/json" -H "Content-type: application/json" -X POST -d '{"text":"e公司讯，龙力退（002604）7月14日晚间公告，公司股票已被深交所决定终止上市，并在退市整理期交易30个交易日，最后交易日为7月14日，将在2020年7月15日被摘牌。公司股票终止上市后，将进
入股转系统进行股份转让。"' http://localhost:5000/abstract

**Comment by HelloWorldlry** [comment]
还没测试呢，在部署sudo docker-compose up这个的时候报的错

**Comment by LowinLi** [comment]
看您发出来的信息，flask启动成功了，没有报错，可以开始尝试post请求看看是否反馈摘要信息

**Comment by HelloWorldlry** [comment]
就一直卡在这儿没反应，ctrl+c退出来才行

**Comment by LowinLi** [comment]
post请求返回什么呢？

**Comment by LowinLi** [comment]
看您发出来的情况看，服务启的都是正常的，没有什么问题，一直卡在这儿是什么意思？它在等待您客户端的post请求。但是我看到您的服务收到GET请求，readme中说是需要发送POST请求：

**Comment by LowinLi** [comment]
curl -H "Accept: application/json" -H "Content-type: application/json" -X POST -d '{"text":"e公司讯，龙力退（002604）7月14日晚间公告，公司股票已被深交所决定终止上市，并在退市整理期交易30个交易日，最后交易日为7月14日，将在2020年7月15日被摘牌。公司股票终止上市后，将进
入股转系统进行股份转让。"' http://localhost:5000/abstract

**Comment by HelloWorldlry** [comment]
就也输入不了什么东西，我就只能ctrl+c退出来了

**Comment by LowinLi** [comment]
我想您可以不太清楚服务端和客户端的意思。
您部署好后，另起一个窗口，输入：
```
curl -H "Accept: application/json" -H "Content-type: application/json" -X POST -d '{"text":"e公司讯，龙力退（002604）7月14日晚间公告，公司股票已被深交所决定终止上市，并在退市整理期交易30个交易日，最后交易日为7月14日，将在2020年7月15日被摘牌。公司股票终止上市后，将进
入股转系统进行股份转让。"' http://localhost:5000/abstract
```
端口别再弄错了，保持一致，因为我看您有个截图部署在了5060端口上

**Comment by HelloWorldlry** [comment]
我linux命令都不太懂，因为你有已经训练好的模型，我就想直接拿来先用着，现在想想我要将我的数据从数据库里面取出来该怎么调用这个模型......我还是自己慢慢弄吧。。。
