### ISSUE TITLE
请问modle.py里的encoder decoder是图自编码器吗

### ISSUE THREAD

**Issue by starryscholar** [LowinLi/Text-Summarizer-Pytorch-Chinese#22]
请问modle.py里的encoder decoder是图自编码器吗

**Comment by LowinLi** [comment]
图自编码器是做图像处理的吗，我没研究过。这个脚本来自这个项目

https://github.com/rohithreddy024/Text-Summarizer-Pytorch

**Comment by starryscholar** [comment]
> 图自编码器是做图像处理的吗，我没研究过。这个脚本来自这个项目
> 
> https://github.com/rohithreddy024/Text-Summarizer-Pytorch

好的，谢谢
