### ISSUE TITLE
测试您提供的demo.tar得到的结果与报道的不符

### ISSUE THREAD

**Issue by lsq960124** [LowinLi/Text-Summarizer-Pytorch-Chinese#29]
使用已训练好的demo.tar 得到的结果为：
rouge1： 0.3474
rouge2：0.1689
rouge3：0.3382
与你提供的存在一定的差距，参数没有调整，请问可能原因？

2021-09-14 19:13:31,941 - data_util.log - INFO - demo.tar rouge_1:0.3474 rouge_2:0.1689 rouge_l:0.3382

**Comment by LowinLi** [comment]
> 使用已训练好的demo.tar 得到的结果为：
> rouge1： 0.3474
> rouge2：0.1689
> rouge3：0.3382
> 与你提供的存在一定的差距，参数没有调整，请问可能原因？
> 
> 2021-09-14 19:13:31,941 - data_util.log - INFO - demo.tar rouge_1:0.3474 rouge_2:0.1689 rouge_l:0.3382

验证集还是测试集？
看你给的跟测试集指标差不多，这个随机因素，可能跟tensorflow版本有关？

**Comment by lsq960124** [comment]
这个代码是基于torch的呀。我猜测应该是和随机有关。因为代码make_data_files里面随机挑选了1个bin文件（100条测试数据）作为测试集来得到最终指标。可能我随机挑选的测试文件和你的文件有出入。

**Comment by lsq960124** [comment]
很感谢你这么及时的回复。此外，还有个问题请教，你是否在全量的数据（main_valid）中测试过模型的性能？

**Comment by LowinLi** [comment]
这个仓库有一年多了，除了readme写的，其他的试验我已经不记得了 :)
