### ISSUE TITLE
博主，您好。我在运行train.py时没有saved_models/0005000.tar这个路径！还请您看到能回复，谢谢。

### ISSUE THREAD

**Issue by SoonYoon** [LowinLi/Text-Summarizer-Pytorch-Chinese#32]
![QQ图片20211213231513](https://user-images.githubusercontent.com/94044397/145838095-6599097e-7e3a-4a6a-8962-509461288397.png)

**Comment by LowinLi** [comment]
我想有可能需要手动添加一下目录data/saved_models

**Comment by SoonYoon** [comment]
您好，博主。方便给个联系方式吗？上面这个问题我已经解决就和您所说的一样。但是昨晚运行看代码时有些问题确实不会，想请教您，还希望您能慷慨解囊。谢谢！
