### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by xuerzhuo1997** [LowinLi/Text-Summarizer-Pytorch-Chinese#36]
FileNotFoundError: [Errno 2] No such file or directory: 'data/saved_models/0005000.tar'这个问题是需要自己设置data/saved_models/这个文件夹吗？

**Comment by LowinLi** [comment]
嗯嗯，看来是的

**Comment by xuerzhuo1997** [comment]
您好，尔卓已经收到您的邮件。感谢您的来信，祝您生活愉快！
