### ISSUE TITLE
用demo.tar现有模型去跑得不到博主的readme.md文件中提到的rouge的分数？

### ISSUE THREAD

**Issue by PYMAQ** [LowinLi/Text-Summarizer-Pytorch-Chinese#8]
2020-12-14 22:08:31,509 - data_util.log - INFO - demo.tar rouge_1:0.1721 rouge_2:0.0574 rouge_l:0.1639
得到的是这个
我是根据makefile代码对数据集进行处理后得到几个文件夹的数据集预处理后的文件，然后直接eval脚本进行测试得到上面的分数，是否哪一步有问题呢？

**Comment by PYMAQ** [comment]
还有个疑问是，readme.md里面给的词表和项目中已经有的词表不一致？里面有少许不同，影响大吗？感谢博主解答~~~

**Comment by PYMAQ** [comment]
话说博主，我看到reward发现你这个还可以增量训练?也就是这个模型训练完后还可以再在这个模型的基础上再次训练？？

**Comment by PYMAQ** [comment]
好像没找到在哪里设置epoch？博主是设置了早停法吗？

**Comment by LowinLi** [comment]
> 好像没找到在哪里设置epoch？博主是设置了早停法吗？

在data_util.config 中的 max_iterations修改训练batch轮数，没有设置epoch

**Comment by LowinLi** [comment]
> 话说博主，我看到reward发现你这个还可以增量训练?也就是这个模型训练完后还可以再在这个模型的基础上再次训练？？

在原英文项目、和论文中介绍了两种训练方试，分段训练

**Comment by LowinLi** [comment]
> 还有个疑问是，readme.md里面给的词表和项目中已经有的词表不一致？里面有少许不同，影响大吗？感谢博主解答~~~

您的项目语料不一样、词表不一样，最好重新训练一遍。我这里词表是根据训练语料的词频从高到低排下来的。

**Comment by LowinLi** [comment]
> 2020-12-14 22:08:31,509 - data_util.log - INFO - demo.tar rouge_1:0.1721 rouge_2:0.0574 rouge_l:0.1639
> 得到的是这个
> 我是根据makefile代码对数据集进行处理后得到几个文件夹的数据集预处理后的文件，然后直接eval脚本进行测试得到上面的分数，是否哪一步有问题呢？

抱歉时间有点长了，我也忘记了demo.tar的模型是我训练到哪个阶段的。建议您完整跑一遍流程，看看您训练的模型指标有多少。

**Comment by PYMAQ** [comment]
> > 还有个疑问是，readme.md里面给的词表和项目中已经有的词表不一致？里面有少许不同，影响大吗？感谢博主解答~~~
> 
> 您的项目语料不一样、词表不一样，最好重新训练一遍。我这里词表是根据训练语料的词频从高到低排下来的。

这个词表是根据项目中哪块代码生成的吗？

**Comment by LowinLi** [comment]
> > > 还有个疑问是，readme.md里面给的词表和项目中已经有的词表不一致？里面有少许不同，影响大吗？感谢博主解答~~~
> > 
> > 
> > 您的项目语料不一样、词表不一样，最好重新训练一遍。我这里词表是根据训练语料的词频从高到低排下来的。
> 
> 这个词表是根据项目中哪块代码生成的吗？

这里

https://github.com/LowinLi/Text-Summarizer-Pytorch-Chinese/blob/ff090096878331ee2e9e022f57ab8657eb6a456f/make_data_files.py#L84

**Comment by PYMAQ** [comment]
感谢！！

**Comment by LowinLi** [comment]
不客气，感谢您的支持
