### ISSUE TITLE
尝试更换数据集但是出现下面的错误？

### ISSUE THREAD

**Issue by PYMAQ** [LowinLi/Text-Summarizer-Pytorch-Chinese#9]
File "C:\Program Files\JetBrains\PyCharm 2020.2.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "G:/all_summarization/Text-Summarizer-Pytorch-Chinese/make_data_files.py", line 169, in <module>
    samples = random.sample(set(bin_chunks[:-1]), 2)
  File "C:\Users\ympeng\.conda\envs\pytorch\lib\random.py", line 320, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative

说是这一行代码产生的：    samples = random.sample(set(bin_chunks[:-1]), 2)

1.请问有什么解决办法吗？
2.难道是我的数据集中摘要的长度过长？
3.本项目是否对数据集的文本长度有限制？如果有限制是在哪里改呢？
感谢博主~~~

**Comment by PYMAQ** [comment]
还是说我的数据集太少了，总共1千多条，切分成训练集，测试集，验证集。

**Comment by LowinLi** [comment]
数据集有点少，这个报错看来是语料有问题

**Comment by PYMAQ** [comment]
CHUNK_SIZE = 100  # num examples per chunk, for the chunked data
这个设置小一点就可以了，搞定了。谢谢！！！

**Comment by LowinLi** [comment]
1千数据是有点少。建议如果效果不尽如人意的话，可以先用公开数据集训练，再用项目数据集增量训练

**Comment by PYMAQ** [comment]
那个参考摘要和生成摘要的长度可以自己设定吗？

**Comment by LowinLi** [comment]
> 
> 
> 那个参考摘要和生成摘要的长度可以自己设定吗？
这里可以改：
https://github.com/LowinLi/Text-Summarizer-Pytorch-Chinese/blob/master/data_util/config.py#L12
